# Generated by Django 2.1 on 2018-08-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(default='cse', max_length=10)),
                ('regulation', models.CharField(default='r16', max_length=10)),
                ('semester', models.CharField(default='1-1', max_length=10)),
                ('subname', models.CharField(max_length=10)),
                ('pdf', models.FileField(upload_to='pdf')),
                ('unit', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='videourls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=100)),
                ('Topicpdf', models.FileField(blank=True, default='x', null=True, upload_to='pdf')),
                ('Topicurl', models.URLField(blank=True, null=True)),
                ('subname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppComponent1.Branches')),
            ],
        ),
    ]
