# Generated by Django 2.1 on 2018-09-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='clgname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='branches',
            name='teachername',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='branches',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videourls',
            name='clgname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='videourls',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branches',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='unit',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='videourls',
            name='subname',
            field=models.CharField(max_length=100),
        ),
    ]
