# Generated by Django 2.1 on 2018-09-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent1', '0002_auto_20180902_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourls',
            name='teachername',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
