# Generated by Django 2.1 on 2018-09-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppComponent1', '0003_videourls_teachername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videourls',
            name='teachername',
        ),
    ]
